title: PandoramicView Test Site
author: PandoramicView
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is where the silly, non-legible SEO text goes. That's alright, tho,
  I'm more concerned with clarity than discoverability.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
